name: Savitar
description: A project that uses Jaguar-dart

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  angular: ^5.1.0
  angular_components: ^0.10.1
  analyzer: ^0.33.6+1
  build: ^1.0.0
  logging: ^0.11.0
  source_gen: ^0.9.0
  meta: ^1.1.5
  jaguar: ^2.4.19
  jaguar_orm: ^2.2.1
  jaguar_query_postgres: ^2.2.2
  jaguar_jwt: ^2.1.5
  jaguar_reflect: ^2.4.6
  jaguar_serializer: ^2.2.0
  jaguar_cache: ^2.1.2
  jaguar_session_jwt: ^2.2.1
  jaguar_auth: ^2.4.0
  jaguar_resty: ^2.8.0
  jaguar_dev_proxy: ^2.4.4
  jaguar_client: ^2.4.0
  jaguar_cors: ^2.4.4
  jaguar_throttle: ^2.4.1
  stencil: ^2.1.1
  http: ^0.11.3
  path: ^1.6.2
  package_config: ^1.0.5
  safe_config: ^2.0.2
  dart_browser_loader: ^0.0.2
  yaml: ^2.1.15

dev_dependencies:
  angular_test: ^2.1.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
  test: ^1.5.1
  jaguar_orm_gen: ^2.2.26
  jaguar_generator: ^2.4.5
  jaguar_hotreload: ^2.0.2
